/* WebKiln's adapter boundary and local MVP services. A future server adapter can replace this without changing editor UI. */
(function(){
  const STORAGE='webkiln-project-v2';
  const componentRegistry={
    heading:{id:'heading',version:1,category:'core',name:'Heading',fields:['text','level'],allowedParents:['section','container'],responsive:true},
    button:{id:'button',version:1,category:'core',name:'Button',fields:['label','href'],allowedParents:['section','container'],responsive:true},
    container:{id:'container',version:1,category:'layout',name:'Container',fields:['width','padding'],allowedParents:['section','body'],responsive:true},
    navigation:{id:'navigation',version:1,category:'pattern',name:'Navigation',fields:['logo','links'],allowedParents:['body'],responsive:true},
    form:{id:'form',version:1,category:'pattern',name:'Form',fields:['fields','successMessage'],allowedParents:['section','container'],responsive:true}
  };
  const adapter={
    name:'WebKilnCanvasAdapter',engine:'native-compatible',webkilnReady:false,
    getData(){return {schemaVersion:1,html:document.querySelector('#siteCanvas')?.innerHTML||'',selected:document.querySelector('.selected')?.dataset.name||null}},
    loadData(data){if(data?.html){document.querySelector('#siteCanvas').innerHTML=data.html;window.wireSections?.()}},
    select(el){window.select?.(el)},
    execute(command,payload){if(command==='insertComponent')return window.addBlock?.(payload.type);if(command==='delete')return document.querySelector('#deleteBtn')?.click()}
  };
  window.WebKiln={adapter,componentRegistry,projectSchema:{version:1,entities:['site','page','revision','asset','theme','deployment','form']}};
  function toast(title,detail){window.toastMessage?.(title,detail)}
  function projectState(){try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{return {}}}
  function saveProject(next){localStorage.setItem(STORAGE,JSON.stringify(next))}
  function currentPage(){return document.querySelector('.crumb span')?.textContent||'Home'}
  function renderLayers(){const list=document.querySelector('#layerList');if(!list)return;const sections=[...document.querySelectorAll('#siteCanvas .section-block')];list.innerHTML=sections.map((el,i)=>`<div class="layer-row ${el.classList.contains('selected')?'active':''}" data-index="${i}"><span class="layer-icon">${el.dataset.name==='Navigation'?'≡':'▦'}</span><strong>${el.dataset.name||'Section'}</strong><small>${el.hidden?'hidden':''}</small><span class="layer-actions"><button type="button" data-layer-action="up" aria-label="Move up">↑</button><button type="button" data-layer-action="down" aria-label="Move down">↓</button><button type="button" data-layer-action="hide" aria-label="Toggle visibility">◉</button></span></div>`).join('');list.querySelectorAll('.layer-row').forEach(row=>{row.addEventListener('click',e=>{const el=sections[Number(row.dataset.index)];if(e.target.closest('[data-layer-action]'))return;window.select?.(el)});row.querySelectorAll('[data-layer-action]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const el=sections[Number(row.dataset.index)],action=btn.dataset.layerAction;if(action==='hide'){el.hidden=!el.hidden;window.snapshot?.();renderLayers();return}if(action==='up'&&el.previousElementSibling?.classList.contains('section-block'))el.parentNode.insertBefore(el,el.previousElementSibling);if(action==='down'&&el.nextElementSibling?.classList.contains('section-block'))el.parentNode.insertBefore(el.nextElementSibling,el);window.snapshot?.();renderLayers()}))})}
  function persistRevision(label='Autosave'){const state=projectState();state.schemaVersion=1;state.site=state.site||{id:'local-site',title:'Underline Hosting',theme:{}};state.pages=state.pages||{};state.pages[currentPage()]={html:adapter.getData().html,updatedAt:new Date().toISOString()};state.revisions=state.revisions||[];if(label!=='Autosave'||!state.revisions.length){state.revisions.unshift({id:crypto.randomUUID?.()||String(Date.now()),label,createdAt:new Date().toISOString(),page:currentPage(),html:adapter.getData().html})}state.revisions=state.revisions.slice(0,20);saveProject(state);const count=document.querySelector('#revisionCount');if(count)count.textContent=`${state.revisions.length} local checkpoint${state.revisions.length===1?'':'s'}`}
  function renderAssets(){const list=document.querySelector('#assetList');if(!list)return;const assets=projectState().assets||[];list.innerHTML=assets.length?assets.map(a=>`<article class="asset-card"><div class="asset-thumb">${a.kind==='image'?'▧':'▤'}</div><strong title="${a.name}">${a.name}</strong><small>${a.size||'local asset'}</small></article>`).join(''):'<p class="panel-note">No assets yet. Add images, logos, documents, or video references here.</p>'}
  function addAsset(file){const valid=['image/','application/pdf','video/'].some(type=>file.type.startsWith(type));if(!valid||file.size>10*1024*1024){toast('Asset rejected','Use an image, PDF, or video under 10 MB.');return}const state=projectState();state.assets=state.assets||[];state.assets.push({id:crypto.randomUUID?.()||String(Date.now()),name:file.name,size:`${Math.max(1,Math.round(file.size/1024))} KB`,kind:file.type.startsWith('image/')?'image':'file',mime:file.type});saveProject(state);renderAssets();toast('Asset added',`${file.name} is available in the media library.`)}
  function wireMvp(){
    renderLayers();renderAssets();persistRevision();
    const observer=new MutationObserver(()=>{renderLayers();const selected=document.querySelector('.selected');const status=document.querySelector('#selectionStatus');if(status)status.textContent=selected?`${selected.dataset.name||'Section'} selected`:'Nothing selected'});observer.observe(document.querySelector('#siteCanvas'),{subtree:true,childList:true,attributes:true,attributeFilter:['class','hidden']});
    document.querySelector('#assetUploadButton')?.addEventListener('click',()=>document.querySelector('#assetInput')?.click());document.querySelector('#chooseAsset')?.addEventListener('click',()=>document.querySelector('#assetInput')?.click());document.querySelector('#assetInput')?.addEventListener('change',e=>[...e.target.files].forEach(addAsset));const drop=document.querySelector('#assetDrop');drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-active')});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag-active'));drop?.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-active');[...e.dataTransfer.files].forEach(addAsset)});
    document.querySelector('#assetSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.asset-card').forEach(card=>card.hidden=!card.innerText.toLowerCase().includes(q))});document.querySelector('#componentSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.component-row').forEach(row=>row.hidden=!row.innerText.toLowerCase().includes(q))});
    document.querySelectorAll('.component-row').forEach(row=>row.addEventListener('click',()=>{const type=row.dataset.component;if(type==='form')window.addBlock?.('form');else if(type==='navigation')toast('Navigation component','Select the Navigation section to edit its links.');else if(type==='heading')window.addBlock?.('hero');else window.addBlock?.('features');toast(`${row.innerText.split('\n')[0]} added`,'The new component is selected on the canvas.')}));
    document.querySelector('#checkpointBtn')?.addEventListener('click',()=>{persistRevision('Named checkpoint');toast('Checkpoint saved','This local revision can be restored from your project history.')});document.querySelector('#openSiteSetup')?.addEventListener('click',()=>document.querySelector('#setupBtn')?.click());document.querySelector('#codeEditorBtn')?.addEventListener('click',()=>{document.querySelector('#codeModal').hidden=false;document.querySelector('#codeInput').focus()});
    const codeModal=document.querySelector('#codeModal'),closeCode=()=>{codeModal.hidden=true};document.querySelector('#closeCode')?.addEventListener('click',closeCode);document.querySelector('#cancelCode')?.addEventListener('click',closeCode);document.querySelector('#saveCode')?.addEventListener('click',()=>{const state=projectState();state.customCode={html:document.querySelector('#codeInput').value,updatedAt:new Date().toISOString(),sandboxed:true};saveProject(state);closeCode();toast('Sandbox code saved','Custom code is stored for isolated preview mode.')});codeModal?.addEventListener('click',e=>{if(e.target===codeModal)closeCode()});document.querySelectorAll('.code-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.code-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#codeInput').placeholder=`Add page ${btn.textContent} here...`}));
    document.querySelectorAll('.device').forEach(btn=>btn.addEventListener('click',()=>{const size={desktop:1100,tablet:760,mobile:390}[btn.dataset.width];const status=document.querySelector('#canvasSizeStatus');if(status)status.textContent=`Canvas ${size} px`}));
    document.querySelector('#collapseLayers')?.addEventListener('click',()=>document.querySelector('#layerList').classList.toggle('is-collapsed'));
    document.querySelector('#publishBtn')?.addEventListener('click',()=>persistRevision('Published checkpoint'));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s')persistRevision('Manual save')});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wireMvp);else wireMvp();
})();
